ProjetoWEB/ProjetoWEB/Models/ErrorViewModel.cs
namespace ProjetoWEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoWEB/ProjetoWEB/Models/PrioridadeTarefa.cs
namespace ProjetoWEB.Models
{
    public enum PrioridadeTarefa
    {
        Urgente,    // Valor 0 por padrão
        Alta,       // Valor 1
        Media,      // Valor 2
        Baixa       // Valor 3
    }
}

ProjetoWEB/ProjetoWEB/Models/Tarefas.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoWEB.Models
{
    public class Tarefas
    {
        public int ID { get; set; }
        public int ID_Usuario { get; set; }
        public Usuario Usuario { get; set; }
        public string DetalhesTarefa { get; set; }
        public DateTime DataTarefa { get; set; }

       
        public PrioridadeTarefa Prioridadade { get; set; }
    }
}

ProjetoWEB/ProjetoWEB/Models/Usuario.cs
namespace ProjetoWEB.Models
{
    public class Usuario
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
        public DateTime DataNascimento { get; set; }
        public ICollection<Tarefas> Tarefas { get; set; }
    }
}

ProjetoWEB/ProjetoWEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoWEB.Models;
using System.Diagnostics;

namespace ProjetoWEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoWEB/ProjetoWEB/Controllers/TarefasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoWEB.Context;
using ProjetoWEB.Models;

namespace ProjetoWEB.Controllers
{
    public class TarefasController : Controller
    {
        private readonly UsuarioContext _context;
        public TarefasController(UsuarioContext context)
        {
            _context = context;
        }

        public IActionResult Sair()
        {
            return RedirectToAction("Index","Home");
        }

        public IActionResult Editar(int ID)
        {
            var busca = _context.Tarefas.Find(ID);
            return View(busca); 
        }

        [HttpPost]
        public async Task<IActionResult> EditarTarefa(Tarefas tarefas)
        {
            var TarefaBanco = await _context.Tarefas.FindAsync(tarefas.ID);

           if (TarefaBanco != null)
           {
                TarefaBanco.DataTarefa = tarefas.DataTarefa;
                TarefaBanco.DetalhesTarefa = tarefas.DetalhesTarefa;
                TarefaBanco.Prioridadade = tarefas.Prioridadade;

                _context.Update(TarefaBanco);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { ID = tarefas.ID_Usuario });
           }

           return NotFound();

            
        }


        public IActionResult Deletar(int ID)
        {
            var busca = _context.Tarefas.Find(ID);
            return View(busca); 
        }
        [HttpPost]
        public async Task<IActionResult> DeletarTarefa(int id)
        {
            var tarefa = await _context.Tarefas.FindAsync(id);
            var UsuarioId = tarefa.ID_Usuario;

            if(tarefa == null)
                return NotFound();
            
            _context.Tarefas.Remove(tarefa);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new {ID = UsuarioId});

        }
        public IActionResult Detalhes(int ID)
        {
            var busca = _context.Tarefas.Find(ID);
            return View(busca);
        }
        public async Task<IActionResult> Index(int id)
        {
            //Aqui usamos o viewbag para armazenar o ID do usuario a ser passado
            ViewBag.ID= id;
      
            var listaTarefas = await _context.Tarefas
                                      .Where(t => t.ID_Usuario == id)
                                      .ToListAsync();

            if (listaTarefas == null || !listaTarefas.Any())
            {
                return View();
            }

            return View(listaTarefas);
        }

        public IActionResult Criar(int ID)
        {
            var tarefa = new Tarefas();
            tarefa.ID_Usuario = ID;
            return View(tarefa);
        }

        [HttpPost]
        public async Task<IActionResult> CriarNovaTarefa(Tarefas tarefa)
        {
            _context.Add(tarefa);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = tarefa.ID_Usuario});
        }
    }
}

ProjetoWEB/ProjetoWEB/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoWEB.Context;
using ProjetoWEB.Models;

namespace ProjetoWEB.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioContext _context;

        public UsuarioController(UsuarioContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }
        
        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmaLogin(string email, string senha)
        {
            var usuario = await _context.Usuarios.SingleOrDefaultAsync(u => u.Email == email);
            if (usuario == null)
                return NotFound(new {msg ="Usuario não encontrando!"});

            if (usuario.Senha == senha)
                return RedirectToAction("Index", "Tarefas", new { id = usuario.ID});
            else
                return NotFound();

        }
        [HttpPost]
        public async Task<IActionResult> CadastroUsuario(string email, string senha,DateTime dataNascimento)
        {
            Usuario usuario = new Usuario();
            usuario.Email = email;  
            usuario.Senha = senha;
            usuario.Login = email;
            usuario.DataNascimento = dataNascimento;
            var banco = await _context.Usuarios.SingleOrDefaultAsync(u => u.Email == email);
            if (banco == null)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return Ok(new { mensagem ="Cadastro Realizado com Sucesso." });
            }
            return Ok(new { mensagem = "Usuario ja existente no banco de dados!!!"});
            
        }
       
    }
}

ProjetoWEB/ProjetoWEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center mt-5">
    <h1 class="display-4 font-weight-bold">Bem-vindo ao Gerenciador de Tarefas</h1>
    <p class="lead mt-4">Este projeto foi desenvolvido por Jonathan Sanchez como parte dos estudos de ASP.NET. O objetivo é criar um Gerenciador de Tarefas com funcionalidade de login de usuário. A aplicação permite que os usuários registrem suas contas, façam login e gerenciem suas tarefas pessoais.</p>
    <hr class="my-4">
    <p class="mt-4">Explore e organize suas tarefas de forma fácil e eficiente.</p>
</div>

ProjetoWEB/ProjetoWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoWEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoWEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjetoWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetoWEB/ProjetoWEB/Views/Tarefas/Criar.cshtml
@model ProjetoWEB.Models.Tarefas

@{
    ViewData["Title"] = "Criar nova Tarefa";
}

<h2>Adicionar Nova Tarefa</h2>

<form method="post" asp-action="CriarNovaTarefa">
    <div class="form-group">
        <label class="control-label">Detalhes</label>
        <input type="text" class="form-control" id="detalhesTarefa" name="detalhesTarefa" required />
    </div>

    <div class="form-group">
        <label class="control-label">Data</label>
        <input type="date" id="dataTarefa" name="dataTarefa" class="form-control" required/>
       
    </div>

    <div class="form-group">
        <label class="control-label">Prioridade</label>
        <select id="prioridadeTarefa" name="prioridadeTarefa" class="form-control" asp-items="Html.GetEnumSelectList<PrioridadeTarefa>()">
            <option value="">Selecione a prioridade</option>
        </select>
    </div>

    <input type="hidden" asp-for="ID_Usuario" value="@Model.ID_Usuario" />
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>
<a asp-action="Index" asp-route-id="@Model.ID_Usuario">Voltar</a>

ProjetoWEB/ProjetoWEB/Views/Tarefas/Deletar.cshtml
@model ProjetoWEB.Models.Tarefas
@{
    ViewData["Title"] = "Deletar Tarefa";
}

<h1 style="color: red;">Deseja realmente deletar esse contato ? Essa operação é irreversivel</h1>


<div>
    <dl class="row">
        <dt class="col-sm-2">
            <th>Detalhes da Tarefa</th>
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DetalhesTarefa)
        </dt>
        <dt class="col-sm-2">
            <th>Data da Tarefa</th>
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataTarefa)
        </dt>
        <dt class="col-sm-2">
            <th>Prioridade da Tarefa</th>
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Prioridadade)
        </dt>
    </dl>
</div>



<form asp-action="DeletarTarefa" asp-route-id="@Model.ID">
    <input type="submit" value="Deletar" class="btn btn-danger" />
</form>
<a asp-action="Index" asp-route-id="@Model.ID_Usuario">Voltar</a>

ProjetoWEB/ProjetoWEB/Views/Tarefas/Detalhes.cshtml
@model ProjetoWEB.Models.Tarefas
@{
    ViewData["Title"] = "Detalhes Tarefas";
}

<h1>Detalhes da Tarefa</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DetalhesTarefa)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DetalhesTarefa)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DataTarefa);
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataTarefa)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Prioridadade)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Prioridadade)
        </dt>
    </dl>
</div>

<a asp-action="Editar" asp-route-id="@Model.ID"> Editar</a> |
<a asp-action="Index" asp-route-id="@Model.ID_Usuario">Voltar</a>

ProjetoWEB/ProjetoWEB/Views/Tarefas/Editar.cshtml
@model ProjetoWEB.Models.Tarefas
@{
    ViewData["Title"] = "Editar Tarefa";
}

<h1>Editar Tarefa</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="EditarTarefa">
            <div class="form-group">
                <label class="control-label">Detalhes</label>
                <input asp-for="DetalhesTarefa" type="text" class="form-control" id="detalhesTarefa" name="detalhesTarefa" required />
            </div>

            <div class="form-group">
                <label class="control-label">Data</label>
                <input asp-for="DataTarefa" type="date" id="dataTarefa" name="dataTarefa" class="form-control" required />

            </div>

            <div class="form-group">
                <label class="control-label">Prioridade</label>
                <select asp-for="Prioridadade" id="prioridadeTarefa" name="prioridadeTarefa" class="form-control" asp-items="Html.GetEnumSelectList<PrioridadeTarefa>()">
                    <option value="">Selecione a prioridade</option>
                </select>
            </div>

            <br>
            <input type="hidden" asp-for="ID_Usuario" value="@Model.ID_Usuario" />
            <input type="hidden" asp-for="ID" value="@Model.ID" />
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" /> 
            </div>
        </form>
    </div>
</div>

</hr>
<br>
<div>
    <a asp-action="Index" asp-route-id="@Model.ID_Usuario">Voltar</a>
</div>

ProjetoWEB/ProjetoWEB/Views/Tarefas/Index.cshtml
@model IEnumerable<ProjetoWEB.Models.Tarefas>

@{
    ViewData["Title"] = "Lista de Tarefas";
}

<h2>Lista de Tarefas</h2>

<p>
    <a asp-action="Criar" asp-route-id="@ViewBag.ID">Nova Tarefa</a>

    <a asp-action="Sair" >Sair da Conta</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Detalhes da Tarefa</th>
            <th>Data da Tarefa</th>
            <th>Prioridade</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.DetalhesTarefa</td>
                    <td>@item.DataTarefa.ToShortDateString()</td>
                    <td>@item.Prioridadade</td>
                    <td>
                        <a asp-action="Editar" asp-route-id="@item.ID">Editar</a> |
                        <a asp-action="Detalhes" asp-route-id="@item.ID">Detalhes</a> |
                        <a asp-action="Deletar" asp-route-id="@item.ID">Deletar</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="5">Nenhuma tarefa encontrada.</td>
            </tr>
        }
    </tbody>
</table>

ProjetoWEB/ProjetoWEB/Views/Usuario/Cadastro.cshtml
@model ProjetoWEB.Models.Usuario
@{
    ViewData["Title"] = "Login";
}

<head>
    <link href="~/css/login.css" rel="stylesheet" />
    <link href="/css/erro.css" rel="stylesheet" />
    <script src="~/js/Cadastro.js" type="text/javascript"></script>
    
</head>
<body>
    <h1>Cadastro</h1>

    <form method="post" asp-action="CadastroUsuario">
        <div class="form-group">
            <label for="email">Email: </label>
            <input type="text" id="email" name="email" class="form-control" required/>
            <small class="erro" id="erroEmail"></small>
        </div>
        <div class="form-group">
            <label for="dataNascimento">Data de Nascimento:</label><br />
            <input type="date" id="dataNascimento" name="dataNascimento" required>
            <small class="erro" id="erroData"></small>
        </div>
        <div class="form-group">
            <label for="senha">Senha: </label>
            <input type="password" id="senha" name="senha" class="form-control" required />
            <small class ="erro" id="erroSenha"></small>
        </div>
        <div class="form-group">
            <label for="senhaRepetida">Repetir Senha: </label>
            <input type="password" id="senhaRepetida" name="senhaRepetida" class="form-control" required />
            <small class="erro" id="erroSenhaRepetida"></small>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" >Confirmar</button>
        </div>
    </form>

</body>

<a asp-action="Login">Voltar</a>

ProjetoWEB/ProjetoWEB/Views/Usuario/Login.cshtml
@model ProjetoWEB.Models.Usuario
@{
    ViewData["Title"] = "Login";
}

<head>
    <link href="~/css/login.css" rel="stylesheet" />
    <link href="~/css/erro.css" rel="stylesheet" />
    <script src="~/js/Login.js" type="text/javascript"></script>
</head>
<body>
    <h1>Login</h1>

    <form id="loginForm" method="get" asp-action="ConfirmaLogin">
        <div class="form-group">
            <label for="email">Email: </label>
            <input type="text" id="email" name="email" class="form-control" required/>
            <small class ="erro" id="erroEmail"></small>
        </div>
        <div class="form-group">
            <label for="senha">Senha: </label>
            <input type="password" id="senha" name="senha" class="form-control" required />
            <small class="erro" id="erroSenha"></small>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Confirmar</button>
        </div> 
    </form>
    <a asp-action="Cadastro">Cadastro</a>
</body>